language: perl6
perl6:
  - latest
install:
  - rakudobrew build-panda
  - git clone --recursive git://github.com/tadzik/panda.git && cd panda && perl6 bootstrap.pl
  - panda installdeps .
  - panda --notests install IO::Socket::SSL
script:
  - perl6 -MPanda::Builder -e 'Panda::Builder.build($*CWD)'
  - PERL6LIB=$PWD/blib/lib prove -e perl6 -r t/
sudo: false
